const cfg = window.CLIPPER_CONFIG || { API_BASE_URL: "", DEMO_MODE: true };
const $ = (sel) => document.querySelector(sel);
const state = { campaigns: [], jobs: [], reviews: [], pollTimer: null };
const statusNames = { queued: "ANTRI", processing: "BERJALAN", review: "SIAP REVIEW", error: "GAGAL", blocked: "DIBLOKIR" };
const demoCampaigns = [
  { id: "demo-ai-clips", title: "AI Founder Clips", brand: "Demo Studio", category: "technology", score: 86.5, rate_per_1k: 7, budget_left: 3850, platforms: ["tiktok", "youtube", "instagram"], type: "clipping", verified: true, description: "Use the provided podcast footage. Create native vertical clips with a clear hook and subtitles.", flags: [] },
  { id: "demo-podcast", title: "Podcast Growth Campaign", brand: "North Star Media", category: "education", score: 78.2, rate_per_1k: 4, budget_left: 12400, platforms: ["youtube", "tiktok"], type: "clipping", verified: true, description: "Short educational clips from the official content library. No third-party watermark.", flags: ["9:16 required"] },
  { id: "demo-music", title: "Artist Discovery Clips", brand: "Indie Records", category: "music", score: 69.4, rate_per_1k: 2.5, budget_left: 8200, platforms: ["tiktok", "instagram"], type: "clipping", verified: false, description: "Use official footage and attach the official sound when posting.", flags: ["official audio"] }
];
function money(value) { return value == null ? "—" : `$${Number(value).toLocaleString()}`; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c])); }
function showToast(message) { const el = $("#toast"); el.textContent = message; el.classList.remove("hidden"); setTimeout(() => el.classList.add("hidden"), 2800); }
function api(path, options) { return fetch(`${cfg.API_BASE_URL || ""}${path}`, options).then((r) => { if (!r.ok) throw new Error(`API ${r.status}`); return r.json(); }); }
async function loadCampaigns() {
  try {
    state.campaigns = cfg.DEMO_MODE ? demoCampaigns : (await api("/api/campaigns")).campaigns;
  } catch (error) {
    state.campaigns = [];
    showToast(cfg.DEMO_MODE ? "Demo tidak tersedia" : "API production gagal — tidak menampilkan data demo");
  }
  renderCampaigns();
}
function renderCampaigns() {
  const q = $("#searchInput").value.toLowerCase(); const platform = $("#platformFilter").value; const sort = $("#sortSelect").value;
  let rows = state.campaigns.filter((c) => (!q || `${c.title} ${c.brand} ${c.category}`.toLowerCase().includes(q)) && (!platform || (c.platforms || []).includes(platform)));
  const metric = sort === "rate" ? "rate_per_1k" : sort === "budget" ? "budget_left" : sort === "recency" ? null : "score";
  rows.sort((a, b) => metric ? Number(b[metric] || 0) - Number(a[metric] || 0) : Number(b.priority_components?.recency || 0) - Number(a.priority_components?.recency || 0));
  $("#activeCount").textContent = state.campaigns.length; $("#campaignMeta").textContent = `${rows.length} campaign cocok`;
  $("#campaignGrid").innerHTML = rows.map((c) => `<article class="campaign-card"><div class="card-top"><span class="category-pill">${escapeHtml(c.category)}</span><span class="card-labels">${c.new ? '<b class="new-badge">NEW</b>' : ''}${c.verified ? '<span class="verified">● Verified</span>' : ''}${c.ai_rules_status === "pass" ? '<span class="verified">● AI ready</span>' : '<span class="verified">● AI review</span>'}</span></div><h4>${escapeHtml(c.title)}</h4><p class="brand">${escapeHtml(c.brand)}</p><p class="description">${escapeHtml(c.description || "Campaign siap diproses oleh mesin.")}</p><div class="chips">${(c.platforms || []).map((p) => `<span>${escapeHtml(p)}</span>`).join("")}${(c.flags || []).map((f) => `<span class="flag">${escapeHtml(f)}</span>`).join("")}</div><div class="metrics"><div><small>Priority</small><strong>${Number(c.score || 0).toFixed(1)}</strong></div><div><small>Rate / 1K</small><strong>${money(c.rate_per_1k)}</strong></div><div><small>Competition</small><strong>${escapeHtml(c.competition_proxy?.risk || "proxy")}</strong></div></div><button class="primary-button start-button" data-id="${escapeHtml(c.id)}">Pilih campaign <span>→</span></button></article>`).join("") || '<div class="empty-state">Tidak ada campaign yang cocok.</div>';
  document.querySelectorAll(".start-button").forEach((button) => button.addEventListener("click", () => openCampaign(button.dataset.id)));
}
function openCampaign(id) { const c = state.campaigns.find((x) => x.id === id); if (!c) return; $("#modalContent").innerHTML = `<p class="eyebrow">CAMPAIGN DETAIL</p><h2>${escapeHtml(c.title)}</h2><p class="modal-brand">${escapeHtml(c.brand)} · ${escapeHtml(c.type || "clipping")}</p><div class="rule-preview"><strong>Yang akan dikerjakan mesin</strong><span>Membaca rules dan asset campaign</span><span>Transkripsi dengan AI lokal cloud</span><span>Render 9:16 dengan subtitle</span><span>Validasi sebelum review</span></div><p class="modal-note">Posting tetap dikunci. Anda hanya menerima preview untuk diperiksa.</p><button class="primary-button" id="startJob">Mulai clipping otomatis <span>→</span></button>`; $("#detailModal").classList.remove("hidden"); $("#startJob").addEventListener("click", () => startJob(c)); }
async function startJob(campaign) {
  $("#detailModal").classList.add("hidden");
  const localJob = { id: `local-${Date.now()}`, campaign_id: campaign.id, campaign_title: campaign.title, campaign_brand: campaign.brand, status: "queued", progress: 0, message: "Menunggu worker cloud" }; state.jobs.unshift(localJob); renderJobs(); showView("jobs");
  try {
    if (!cfg.DEMO_MODE) { const response = await api(`/api/campaigns/${encodeURIComponent(campaign.id)}/jobs`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ campaign_id: campaign.id }) }); Object.assign(localJob, response.job); localJob.campaign_title = campaign.title; localJob.campaign_brand = campaign.brand; await triggerWorker(localJob); startPolling(); }
    else simulateJob(localJob);
  } catch (error) { localJob.status = "error"; localJob.message = "Tidak bisa menghubungi worker cloud"; localJob.error = error.message; renderJobs(); }
}
async function triggerWorker(job) { if (!cfg.GITHUB_DISPATCH_URL) return; await fetch(cfg.GITHUB_DISPATCH_URL, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ job_id: job.id, campaign_id: job.campaign_id }) }); }
function simulateJob(job) { const steps = [["Mengantri di worker cloud", 5], ["Membaca rules campaign", 20], ["Mengambil bahan resmi", 38], ["Transkripsi dengan AI", 58], ["Render video vertical", 78], ["Validasi syarat", 94], ["Preview siap direview", 100]]; let i = 0; const tick = () => { if (i >= steps.length) { job.status = "review"; job.message = "2 preview siap direview"; state.reviews = [{ job, title: job.campaign_title, video: "", download_url: null }, { job, title: `${job.campaign_title} · Kandidat 2`, video: "", download_url: null }]; renderJobs(); renderReviews(); return; } job.status = i === 0 ? "queued" : i === steps.length - 1 ? "review" : "processing"; job.message = steps[i][0]; job.progress = steps[i][1]; renderJobs(); i++; setTimeout(tick, 850); }; tick(); }
function statusText(status) { return statusNames[status] || String(status || "UNKNOWN").toUpperCase(); }
function renderJobs() { $("#queueCount").textContent = state.jobs.filter((j) => j.status === "queued" || j.status === "processing").length; $("#jobsList").innerHTML = state.jobs.map((j) => `<article class="job-card"><div class="job-icon ${j.status === "processing" ? "spinning" : ""}">${j.status === "review" ? "✓" : j.status === "error" ? "!" : "◌"}</div><div class="job-main"><div class="job-head"><strong>${escapeHtml(j.campaign_title || j.campaign_id)}</strong><span class="status ${escapeHtml(j.status)}">${statusText(j.status)}</span></div><p><b>${escapeHtml(j.message || "Menunggu update…")}</b>${j.error ? ` · ${escapeHtml(j.error)}` : ""}</p><div class="progress"><i style="width:${j.progress || 0}%"></i></div></div><span class="progress-number">${j.progress || 0}%</span></article>`).join("") || '<div class="empty-state">Belum ada job. Pilih campaign untuk memulai.</div>'; }
async function loadJobs() { if (cfg.DEMO_MODE) return; try { const response = await api("/api/jobs"); state.jobs = response.jobs || []; renderJobs(); for (const job of state.jobs.filter((j) => j.status === "review")) await loadPreviews(job); } catch (error) { showToast("Status worker belum dapat diambil"); } }
async function loadPreviews(job) { try { const response = await api(`/api/jobs/${encodeURIComponent(job.id)}/previews`); for (const preview of response.previews || []) state.reviews.push({ ...preview, title: `${job.campaign_title || "Campaign"} · Kandidat ${preview.rank}`, job }); renderReviews(); } catch (error) { /* keep job visible even if preview endpoint is late */ } }
function startPolling() { if (cfg.DEMO_MODE || state.pollTimer) return; state.pollTimer = setInterval(async () => { await loadJobs(); if (!state.jobs.some((j) => j.status === "queued" || j.status === "processing")) { clearInterval(state.pollTimer); state.pollTimer = null; } }, 10000); }
function renderReviews() { $("#reviewGrid").innerHTML = state.reviews.map((r, i) => `<article class="review-card">${r.video_url || r.download_url ? `<video class="review-video" controls preload="metadata" src="${escapeHtml(r.video_url || r.download_url)}"></video>` : '<div class="preview-placeholder"><span>Preview menunggu URL</span><small>Worker sedang mengunggah hasil</small></div>'}<div class="review-body"><span class="status review">PENDING REVIEW</span><h4>${escapeHtml(r.title || "Clip")}</h4><p>Periksa video penuh dan checklist campaign sebelum download.</p><div class="review-actions">${r.download_url ? `<a class="primary-button download-link" href="${escapeHtml(r.download_url)}" download>Download MP4 <span>↓</span></a>` : '<button class="primary-button" onclick="showToast(\'Download aktif setelah worker mengunggah preview\')">Menunggu file <span>◌</span></button>'}<button class="ghost-button" onclick="showToast('Checklist ada di review manifest')">Checklist</button></div></div></article>`).join("") || '<div class="empty-state">Belum ada preview siap review.</div>'; }
function showView(name) { document.querySelectorAll(".view").forEach((v) => v.classList.add("hidden")); $(`#${name}View`).classList.remove("hidden"); $("#pageTitle").textContent = name === "campaigns" ? "Campaign radar" : name === "jobs" ? "Processing queue" : "Ready for review"; document.querySelectorAll(".nav-item").forEach((n) => n.classList.toggle("active", n.getAttribute("href") === `#${name}`)); }
document.querySelectorAll(".nav-item").forEach((n) => n.addEventListener("click", (e) => { e.preventDefault(); showView(n.getAttribute("href").slice(1)); }));
$("#refreshButton").addEventListener("click", async () => { await loadCampaigns(); await loadJobs(); showToast("Data diperbarui"); }); $("#searchInput").addEventListener("input", renderCampaigns); $("#platformFilter").addEventListener("change", renderCampaigns); $("#sortSelect").addEventListener("change", renderCampaigns); document.querySelectorAll("[data-close]").forEach((x) => x.addEventListener("click", () => $("#detailModal").classList.add("hidden")));
$("#workerStatus").textContent = cfg.DEMO_MODE ? "demo mode" : "connected · polling 10s"; loadCampaigns(); loadJobs();
